version: '3.8'
services:
  loot-database:
    image: postgres:16-alpine
    networks:
      - default
    restart: always
    container_name: service-loot-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: loot
  loot-api:
    build: .
    networks:
      - messaging
      - default
    container_name: service-loot-api
    ports:
      - 3335:3333
    volumes:
      - .:/usr/src/service-loot
    links:
      - loot-database
    depends_on:
      - loot-database
    command: sh -c "/wait; npm ci; npx prisma generate; npx prisma migrate deploy; npx prisma db seed; npm run start:dev"
    environment:
      - WAIT_HOSTS=loot-database:5432,kafka:9092
      - WAIT_TIMEOUT=1000
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=300