@baseUrl = http://localhost:3337
@accessToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZmRhNmMxMC04NmYwLTQ5NDQtYjg1My02YWJmYjQ2ODEyMDciLCJpYXQiOjE2OTg0MjYyMTB9.QsaJxcQGjfzMAWb6JF3dV1bS57KpHnVu-IQr9oYXykBIgBTxaYQFtOWhnGToZMoAfgrQ27yjG1F81vARJKvvDz_QjGHCleQqT2feRzR9KF07sa6zShmOAe4iaX_GVjSvRYo45XxcbvpIfLQoBOwyZPFxlIMa9Ks_GoVJGdY1neoVKnrG5nvzGpVAoOxJvkcUREkbYMIJBW_MYtpn6_46HjQ4pY4z0h0yj69BB87YKAKd3Jb_-uGKZ45G8JiQhYJPv-xkauc2nu0R4hq51koVgq5_BL1Ucal70lrejRcklhc7njS3rhxhrzj75eMh5f8Fij7llrp3HSH-XGMRHXP0jg

# @name create_account
GET {{baseUrl}}/champions
Content-Type: application/json
Authorization: Bearer {{accessToken}}