version: '3.8'
services:
  web-app:
    build: .
    networks:
      - default
    container_name: service-web-app
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/service-web
    command: sh -c "npm ci; npm run dev"