version: '3.8'
services:
  catalog-database:
    image: postgres:16-alpine
    networks:
      - default
    restart: always
    container_name: service-catalog-db
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: catalog
  catalog-api:
    build: .
    networks:
      - default
      - messaging
    container_name: service-catalog-api
    ports:
      - 3336:3333
    volumes:
      - .:/usr/src/service-catalog
    links:
      - catalog-database
    depends_on:
      - catalog-database
    command: sh -c "/wait; npm ci; npx prisma generate; npx prisma migrate deploy; npm run start:dev"
    environment:
      - WAIT_HOSTS=catalog-database:5432,kafka:9092
      - WAIT_TIMEOUT=1000
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=300